 --11
 SELECT CNAME FROM Customers
 WHERE CITY='NAGPUR' OR CITY='DELHI'

 SELECT CNAME FROM Customers
 WHERE CITY in ('NAGPUR','DELHI')

 --12
 SELECT CNAME,BNAME FROM Deposit
 WHERE AMOUNT>4000 and ACTNO<105

 --13
 SELECT * FROM BORROW
 WHERE AMOUNT>=3000 AND AMOUNT<=8000

 SELECT * FROM BORROW
 WHERE AMOUNT BETWEEN 3000 AND 8000

 --14
 SELECT  * FROM Deposit
 WHERE NOT BNAME='ANDHERI'

 --15
 SELECT ACTNO,CNAME,BNAME,AMOUNT FROM Deposit
 WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104

 --b--

 --1
  SELECT TOP 5 * FROM Deposit

  --2
   SELECT TOP 3 * FROM Deposit
   WHERE AMOUNT>1000

   --3
    SELECT TOP 5 LOANNO,CNAME FROM BORROW
	WHERE BNAME<>'ANDHERI'

	--4
	SELECT DISTINCT CITY FROM CuSTOMERS

	--5
		SELECT DISTINCT BNAME FROM BRANCH

		--C--

	--1
	SELECT TOP 50 PERCENT * FROM BORROW

	--2
	SELECT TOP 10 PERCENT * FROM Deposit

	--3
	SELECT TOP 25 PERCENT * FROM Deposit
	WHERE AMOUNT>5000

	--4
	SELECT TOP 10 PERCENT AMOUNT FROM BORROW
	
	--5
		SELECT DISTINCT CITY,CNAME FROM CuSTOMERS

	--6
		SELECT *,(AMOUNT+AMOUNT*0.1) AS 'EXTRA AMOUNT' FROM BORROW

	--7
		SELECT * FROM BORROW
		where LOANNO%2=0


